---
# tasks file for win_service_manage
- name: Install Packages
  win_chocolatey:
    name: "{{ package_name }}" 
    state: present
    params: "{{ parameters }}"
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'

- name: Enable the service
  win_service:
    name: "{{ service_name }}"
    state: started
    state_mode: auto
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'

#- name: Enable the Firewall.
#  win_firewall:
#    state: enabled
#    profiles:
#    - Public

- name: Add the Rule in Firewall
  win_firewall_rule:
    name: "{{ service_name }}"
    action: allow
    local_port: "{{ local_port }}"
    direction: in
    protocol: "{{ protocol_name }}" 
    state: present
    enabled: yes

  
